name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  API_KEY: ""
  OPENAI_API_BASE_URL: "https://api.groq.com/openai/v1/"
  DEFAULT_MODEL_ID: "llama-3.1-70b-versatile"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test -V
      run: cargo run -- -V
    - name: Test -h
      run: cargo run -- -h
    - name: Test -g
      run: cargo run -- -g
    - name: Run unit test
      run: cargo test
