name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  API_KEY: ${{ secrets.API_KEY }}
  OPENAI_API_BASE_URL: "https://api.groq.com/openai/v1/"
  DEFAULT_MODEL_ID: "llama-3.1-70b-versatile"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test -V
      run: cargo run -- -V
    - name: Test -h
      run: cargo run -- -h
    - name: Test -g
      run: cargo run -- -g
    - name: Test Default
      run: cargo run -- examples/link.txt examples/avoid.txt
    - name: Test with Gemma2
      run: cargo run -- examples/link.txt examples/avoid.txt -m gemma2-9b-it
    - name: Test with Mixtral
      run: cargo run -- examples/link.txt examples/avoid.txt -m mixtral-8x7b-32768
