name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  API_KEY: ""
  OPENAI_API_BASE_URL: ""
  DEFAULT_MODEL_ID: ""

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test -V
      run: cargo run -- -V
    - name: Test -h
      run: cargo run -- -h
    - name: Run unit testing
      run: cargo test
    - name: Run linting test
      run: cargo fmt --check
